name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lint:
    name: run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-repo
      - run: pnpm run lint --max-warnings=0
  format:
    name: run format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-repo
      - run: pnpm prettier --check .
  test:
    name: run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-repo
      - run: pnpm run test
  type-check:
    name: run type-check
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-repo
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist
      - name: run type-check
        run: npm run type-check

  build:
    name: run build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-repo
      - run: pnpm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist
  build-demo:
    name: run build (demo)
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-repo
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist
      - name: pnpm build (demo)
        run: pnpm run build
        working-directory: demo
